catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - '@octokit/action@6.1.0'
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - chokidar@4.0.3
  - undici@5.29.0 || 6.22.0
packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': 7.2.0
    '@babel/types': 7.28.6
    '@types/node': 24.10.9
    '@vitest/coverage-v8': 4.0.18
    '@vue/compiler-dom': 3.5.27
    '@vue/compiler-sfc': 3.5.27
    bumpp: 10.4.0
    changelogithub: 14.0.0
    eslint: 9.39.2
    exsolve: 1.0.8
    installed-check: 9.3.0
    knip: 5.82.1
    lint-staged: 16.2.7
    mkdist: 2.4.1
    pkg-pr-new: 0.0.62
    simple-git-hooks: 2.13.1
    typescript: 5.9.3
    unbuild: 3.6.1
    vitest: 4.0.18
    vue-tsc: 3.2.4
  peer:
    '@vue/compiler-core': 3.5.27
    esbuild: 0.27.2
    vue: 3.5.27
  prod:
    '@babel/parser': ^7.27.0
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
onlyBuiltDependencies:
  - simple-git-hooks
