catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - '@octokit/action@6.1.0'
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - chokidar@4.0.3
  - undici@5.29.0 || 6.22.0
packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': 7.6.1
    '@babel/types': 7.29.0
    '@types/node': 24.11.0
    '@vitest/coverage-v8': 4.0.18
    '@vue/compiler-dom': 3.5.29
    '@vue/compiler-sfc': 3.5.29
    bumpp: 10.4.1
    changelogithub: 14.0.0
    eslint: 10.0.2
    exsolve: 1.0.8
    installed-check: 10.0.1
    knip: 5.85.0
    lint-staged: 16.3.1
    mkdist: 2.4.1
    pkg-pr-new: 0.0.65
    simple-git-hooks: 2.13.1
    typescript: 5.9.3
    unbuild: 3.6.1
    vitest: 4.0.18
    vue-tsc: 3.2.5
  peer:
    '@vue/compiler-core': 3.5.29
    esbuild: 0.27.3
    vue: 3.5.29
  prod:
    '@babel/parser': ^7.27.0
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
onlyBuiltDependencies:
  - simple-git-hooks
