packages:
  - playground
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
onlyBuiltDependencies:
  - simple-git-hooks
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - '@octokit/plugin-paginate-rest@9.2.2'
